"""initial schema

Revision ID: 20260716_0001
Revises:
Create Date: 2026-07-16 16:38:05.022837
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '20260716_0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('total_budget', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('current_stage', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_code'), 'projects', ['code'], unique=True)
    op.create_index(op.f('ix_projects_name'), 'projects', ['name'], unique=False)
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('annual_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('budget', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('pain_points', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'year', name='uq_project_year')
    )
    op.create_index(op.f('ix_annual_plans_project_id'), 'annual_plans', ['project_id'], unique=False)
    op.create_index(op.f('ix_annual_plans_year'), 'annual_plans', ['year'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=60), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('before_data', sa.JSON(), nullable=True),
    sa.Column('after_data', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_table('project_access',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'project_id', name='uq_user_project_access')
    )
    op.create_index(op.f('ix_project_access_project_id'), 'project_access', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_access_user_id'), 'project_access', ['user_id'], unique=False)
    op.create_table('user_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('csrf_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_sessions_expires_at'), 'user_sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_user_sessions_token_hash'), 'user_sessions', ['token_hash'], unique=True)
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=True)
    op.create_table('delivery_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('annual_plan_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('target', sa.Text(), nullable=False),
    sa.Column('budget', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('frozen_at', sa.DateTime(), nullable=True),
    sa.Column('released_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['annual_plan_id'], ['annual_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('annual_plan_id', 'code', name='uq_plan_version_code')
    )
    op.create_index(op.f('ix_delivery_versions_annual_plan_id'), 'delivery_versions', ['annual_plan_id'], unique=False)
    op.create_index(op.f('ix_delivery_versions_code'), 'delivery_versions', ['code'], unique=False)
    op.create_index(op.f('ix_delivery_versions_status'), 'delivery_versions', ['status'], unique=False)
    op.create_table('change_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('change_type', sa.String(length=40), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('requested_by', sa.Integer(), nullable=False),
    sa.Column('decided_by', sa.Integer(), nullable=True),
    sa.Column('decision_note', sa.Text(), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('applied_by', sa.Integer(), nullable=True),
    sa.Column('applied_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['applied_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['decided_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['delivery_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_change_requests_status'), 'change_requests', ['status'], unique=False)
    op.create_index(op.f('ix_change_requests_version_id'), 'change_requests', ['version_id'], unique=False)
    op.create_table('funding_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('annual_plan_id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('applicant_id', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['annual_plan_id'], ['annual_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['applicant_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['version_id'], ['delivery_versions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_funding_applications_annual_plan_id'), 'funding_applications', ['annual_plan_id'], unique=False)
    op.create_index(op.f('ix_funding_applications_project_id'), 'funding_applications', ['project_id'], unique=False)
    op.create_index(op.f('ix_funding_applications_status'), 'funding_applications', ['status'], unique=False)
    op.create_index(op.f('ix_funding_applications_version_id'), 'funding_applications', ['version_id'], unique=False)
    op.create_table('requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('annual_plan_id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('stakeholder_role', sa.String(length=20), nullable=False),
    sa.Column('estimated_budget', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('allocated_budget', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('actual_cost', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('source_requirement_id', sa.Integer(), nullable=True),
    sa.Column('assignee_id', sa.Integer(), nullable=True),
    sa.Column('estimated_hours', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('actual_hours', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['annual_plan_id'], ['annual_plans.id'], name='fk_requirements_annual_plan_id_annual_plans', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['source_requirement_id'], ['requirements.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['version_id'], ['delivery_versions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_requirements_annual_plan_id'), 'requirements', ['annual_plan_id'], unique=False)
    op.create_index(op.f('ix_requirements_assignee_id'), 'requirements', ['assignee_id'], unique=False)
    op.create_index(op.f('ix_requirements_code'), 'requirements', ['code'], unique=True)
    op.create_index(op.f('ix_requirements_priority'), 'requirements', ['priority'], unique=False)
    op.create_index(op.f('ix_requirements_project_id'), 'requirements', ['project_id'], unique=False)
    op.create_index(op.f('ix_requirements_requester_id'), 'requirements', ['requester_id'], unique=False)
    op.create_index('ix_requirements_scope', 'requirements', ['project_id', 'annual_plan_id', 'version_id'], unique=False)
    op.create_index(op.f('ix_requirements_status'), 'requirements', ['status'], unique=False)
    op.create_index(op.f('ix_requirements_title'), 'requirements', ['title'], unique=False)
    op.create_index(op.f('ix_requirements_version_id'), 'requirements', ['version_id'], unique=False)
    op.create_table('version_baselines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['delivery_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_version_baselines_version_id'), 'version_baselines', ['version_id'], unique=False)
    op.create_table('budget_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('annual_plan_id', sa.Integer(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.Column('requirement_id', sa.Integer(), nullable=True),
    sa.Column('entry_type', sa.String(length=30), nullable=False),
    sa.Column('amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('occurred_on', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['annual_plan_id'], ['annual_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['version_id'], ['delivery_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_budget_entries_annual_plan_id'), 'budget_entries', ['annual_plan_id'], unique=False)
    op.create_index(op.f('ix_budget_entries_entry_type'), 'budget_entries', ['entry_type'], unique=False)
    op.create_index(op.f('ix_budget_entries_project_id'), 'budget_entries', ['project_id'], unique=False)
    op.create_index(op.f('ix_budget_entries_requirement_id'), 'budget_entries', ['requirement_id'], unique=False)
    op.create_index(op.f('ix_budget_entries_version_id'), 'budget_entries', ['version_id'], unique=False)
    op.create_table('deliverables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('annual_plan_id', sa.Integer(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.Column('requirement_id', sa.Integer(), nullable=True),
    sa.Column('stage', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('storage_key', sa.String(length=500), nullable=True),
    sa.Column('content_type', sa.String(length=150), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['annual_plan_id'], ['annual_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['delivery_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_index(op.f('ix_deliverables_annual_plan_id'), 'deliverables', ['annual_plan_id'], unique=False)
    op.create_index(op.f('ix_deliverables_project_id'), 'deliverables', ['project_id'], unique=False)
    op.create_index(op.f('ix_deliverables_requirement_id'), 'deliverables', ['requirement_id'], unique=False)
    op.create_index(op.f('ix_deliverables_stage'), 'deliverables', ['stage'], unique=False)
    op.create_index(op.f('ix_deliverables_version_id'), 'deliverables', ['version_id'], unique=False)
    op.create_table('operation_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.Column('requirement_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('feedback_type', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reporter_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['version_id'], ['delivery_versions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operation_feedback_project_id'), 'operation_feedback', ['project_id'], unique=False)
    op.create_index(op.f('ix_operation_feedback_requirement_id'), 'operation_feedback', ['requirement_id'], unique=False)
    op.create_index(op.f('ix_operation_feedback_status'), 'operation_feedback', ['status'], unique=False)
    op.create_index(op.f('ix_operation_feedback_version_id'), 'operation_feedback', ['version_id'], unique=False)
    op.create_table('requirement_status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requirement_id', sa.Integer(), nullable=False),
    sa.Column('from_status', sa.String(length=20), nullable=False),
    sa.Column('to_status', sa.String(length=20), nullable=False),
    sa.Column('transition_note', sa.Text(), nullable=False),
    sa.Column('changed_by', sa.Integer(), nullable=False),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_requirement_status_history_changed_at'), 'requirement_status_history', ['changed_at'], unique=False)
    op.create_index(op.f('ix_requirement_status_history_changed_by'), 'requirement_status_history', ['changed_by'], unique=False)
    op.create_index(op.f('ix_requirement_status_history_requirement_id'), 'requirement_status_history', ['requirement_id'], unique=False)
    op.create_index(op.f('ix_requirement_status_history_to_status'), 'requirement_status_history', ['to_status'], unique=False)
    op.create_table('requirement_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requirement_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('requirement_id', 'tag_id', name='uq_requirement_tag')
    )
    op.create_index(op.f('ix_requirement_tags_requirement_id'), 'requirement_tags', ['requirement_id'], unique=False)
    op.create_index(op.f('ix_requirement_tags_tag_id'), 'requirement_tags', ['tag_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_requirement_tags_tag_id'), table_name='requirement_tags')
    op.drop_index(op.f('ix_requirement_tags_requirement_id'), table_name='requirement_tags')
    op.drop_table('requirement_tags')
    op.drop_index(op.f('ix_requirement_status_history_to_status'), table_name='requirement_status_history')
    op.drop_index(op.f('ix_requirement_status_history_requirement_id'), table_name='requirement_status_history')
    op.drop_index(op.f('ix_requirement_status_history_changed_by'), table_name='requirement_status_history')
    op.drop_index(op.f('ix_requirement_status_history_changed_at'), table_name='requirement_status_history')
    op.drop_table('requirement_status_history')
    op.drop_index(op.f('ix_operation_feedback_version_id'), table_name='operation_feedback')
    op.drop_index(op.f('ix_operation_feedback_status'), table_name='operation_feedback')
    op.drop_index(op.f('ix_operation_feedback_requirement_id'), table_name='operation_feedback')
    op.drop_index(op.f('ix_operation_feedback_project_id'), table_name='operation_feedback')
    op.drop_table('operation_feedback')
    op.drop_index(op.f('ix_deliverables_version_id'), table_name='deliverables')
    op.drop_index(op.f('ix_deliverables_stage'), table_name='deliverables')
    op.drop_index(op.f('ix_deliverables_requirement_id'), table_name='deliverables')
    op.drop_index(op.f('ix_deliverables_project_id'), table_name='deliverables')
    op.drop_index(op.f('ix_deliverables_annual_plan_id'), table_name='deliverables')
    op.drop_table('deliverables')
    op.drop_index(op.f('ix_budget_entries_version_id'), table_name='budget_entries')
    op.drop_index(op.f('ix_budget_entries_requirement_id'), table_name='budget_entries')
    op.drop_index(op.f('ix_budget_entries_project_id'), table_name='budget_entries')
    op.drop_index(op.f('ix_budget_entries_entry_type'), table_name='budget_entries')
    op.drop_index(op.f('ix_budget_entries_annual_plan_id'), table_name='budget_entries')
    op.drop_table('budget_entries')
    op.drop_index(op.f('ix_version_baselines_version_id'), table_name='version_baselines')
    op.drop_table('version_baselines')
    op.drop_index(op.f('ix_requirements_version_id'), table_name='requirements')
    op.drop_index(op.f('ix_requirements_title'), table_name='requirements')
    op.drop_index(op.f('ix_requirements_status'), table_name='requirements')
    op.drop_index('ix_requirements_scope', table_name='requirements')
    op.drop_index(op.f('ix_requirements_requester_id'), table_name='requirements')
    op.drop_index(op.f('ix_requirements_project_id'), table_name='requirements')
    op.drop_index(op.f('ix_requirements_priority'), table_name='requirements')
    op.drop_index(op.f('ix_requirements_code'), table_name='requirements')
    op.drop_index(op.f('ix_requirements_assignee_id'), table_name='requirements')
    op.drop_index(op.f('ix_requirements_annual_plan_id'), table_name='requirements')
    op.drop_table('requirements')
    op.drop_index(op.f('ix_funding_applications_version_id'), table_name='funding_applications')
    op.drop_index(op.f('ix_funding_applications_status'), table_name='funding_applications')
    op.drop_index(op.f('ix_funding_applications_project_id'), table_name='funding_applications')
    op.drop_index(op.f('ix_funding_applications_annual_plan_id'), table_name='funding_applications')
    op.drop_table('funding_applications')
    op.drop_index(op.f('ix_change_requests_version_id'), table_name='change_requests')
    op.drop_index(op.f('ix_change_requests_status'), table_name='change_requests')
    op.drop_table('change_requests')
    op.drop_index(op.f('ix_delivery_versions_status'), table_name='delivery_versions')
    op.drop_index(op.f('ix_delivery_versions_code'), table_name='delivery_versions')
    op.drop_index(op.f('ix_delivery_versions_annual_plan_id'), table_name='delivery_versions')
    op.drop_table('delivery_versions')
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_token_hash'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_expires_at'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index(op.f('ix_project_access_user_id'), table_name='project_access')
    op.drop_index(op.f('ix_project_access_project_id'), table_name='project_access')
    op.drop_table('project_access')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_annual_plans_year'), table_name='annual_plans')
    op.drop_index(op.f('ix_annual_plans_project_id'), table_name='annual_plans')
    op.drop_table('annual_plans')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_projects_name'), table_name='projects')
    op.drop_index(op.f('ix_projects_code'), table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
