import { AlertCircle, ArrowRight, BriefcaseBusiness, Check, ClipboardCheck, Download, ExternalLink, FileClock, FileStack, Filter, KeyRound, LockKeyhole, Plus, Search, ShieldCheck, Tags, UserCog, Users, X } from 'lucide-react';
import { useEffect, useMemo, useState, type FormEvent } from 'react';
import { useNavigate } from 'react-router-dom';
import { api, unwrapItems } from '../api';
import { useApp, useApiData } from '../state/AppContext';
import { Button, DataState, EmptyState, Metric, Modal, PageHeader, Section, StatusBadge, formatMoney, statusTone } from '../components/UI';

type SearchEntityType='project'|'requirement'|'version'|'artifact'|'operation';
interface SearchResult{id:string;resourceId:string;entityType:SearchEntityType;type:string;title:string;subtitle:string;status:string;path:string;projectId:string;yearId:string;versionId:string}
interface SearchApiItem{id:string|number;type:string;title?:string;code?:string;status?:string;project_id?:string|number;project_name?:string;annual_plan_id?:string|number|null;version_id?:string|number|null;version_name?:string;requirement_id?:string|number|null;estimated_budget?:string|number;stage?:string|number;year?:string|number;path?:string;subtitle?:string}
const requirementStatusLabels:Record<string,string>={draft:'草稿',planning:'规划中',scheduled:'已排期',developing:'研发中',acceptance:'待验收',online:'已上线运维',closed:'已关闭',rejected:'已驳回',suspended:'已暂停',cancelled:'已取消',changing:'变更中',returned:'已退回'};
const operationStatusLabels:Record<string,string>={open:'待评估',processing:'处理中',resolved:'已解决',closed:'已关闭'};
const artifactStatusLabels:Record<string,string>={draft:'待提交',submitted:'审批中',approved:'已审批',rejected:'已驳回'};
const versionStatusLabels:Record<string,string>={draft:'规划中',frozen:'已冻结',released:'已发布'};

export function GlobalSearchPage(){
  const {options,user,setSelectedProject,setSelectedYear,setSelectedVersion}=useApp();const navigate=useNavigate();const [query,setQuery]=useState('');const [submitted,setSubmitted]=useState('');const [results,setResults]=useState<SearchResult[]>([]);const [loading,setLoading]=useState(false);const [error,setError]=useState('');
  const canSeeMoney=['admin','leader','manager','sales'].includes(user?.role??'');
  const projectName=(item:Record<string,unknown>)=>String(item.project_name??options.projects.find(project=>project.id===String(item.project_id))?.name??`项目 #${item.project_id??'-'}`);
  const versionName=(item:Record<string,unknown>)=>item.version_id?String(item.version_name??options.versions.find(version=>version.id===String(item.version_id))?.name??`版本 #${item.version_id}`):'待规划';
  function normalizeResult(item:SearchApiItem):SearchResult{
    const entityType=(['project','requirement','version','artifact','operation'].includes(item.type)?item.type:'project') as SearchEntityType;
    const labels:Record<SearchEntityType,string>={project:'项目',requirement:'需求',version:'版本',artifact:'成果物',operation:'运营工单'};
    const versionId=String(item.version_id??(entityType==='version'?item.id:'')??'');
    const versionOption=options.versions.find(version=>version.id===versionId);
    const yearId=String(item.annual_plan_id??versionOption?.parentId??'');
    const yearOption=options.years.find(year=>year.id===yearId);
    const projectId=String(item.project_id??yearOption?.parentId??'');
    const rawStatus=String(item.status??'');
    const status=entityType==='requirement'?requirementStatusLabels[rawStatus]??rawStatus:entityType==='operation'?operationStatusLabels[rawStatus]??rawStatus:entityType==='artifact'?artifactStatusLabels[rawStatus]??rawStatus:entityType==='version'?versionStatusLabels[rawStatus]??rawStatus:rawStatus||'匹配';
    const record=item as unknown as Record<string,unknown>;
    let subtitle='';
    if(entityType==='requirement'){const parts=[projectName(record),versionName(record),status];if(canSeeMoney&&item.estimated_budget!==undefined)parts.push(`资金占用 ${formatMoney(Number(item.estimated_budget))}`);subtitle=parts.join(' · ');}
    else if(entityType==='project')subtitle=String(item.code??'规划项目');
    else if(entityType==='version')subtitle=[projectName(record),item.year?`${item.year} 年`:null,status].filter(Boolean).join(' · ');
    else if(entityType==='artifact')subtitle=[projectName(record),item.stage?`阶段 ${item.stage}`:null,status].filter(Boolean).join(' · ');
    else subtitle=[projectName(record),versionId?versionName(record):null,status].filter(Boolean).join(' · ');
    const params=new URLSearchParams();
    if(projectId)params.set('project_id',projectId);
    if(yearId)params.set('annual_plan_id',yearId);
    if(versionId)params.set('version_id',versionId);
    const resourceId=String(item.id);
    const id=String(item.code??item.id);
    let route='/search';
    if(entityType==='project'){route='/projects';params.set('target_id',resourceId);}
    if(entityType==='requirement'){route='/requirements';params.set('q',id);params.set('requirement_id',id);if(!versionId)params.set('planning_pool','true');}
    if(entityType==='version'){route='/versions';params.set('target_id',resourceId);}
    if(entityType==='artifact'){route='/deliverables';if(item.stage)params.set('stage',String(item.stage));params.set('artifact_id',resourceId);}
    if(entityType==='operation'){route='/operations';params.set('operation_id',resourceId);}
    return{id,resourceId,entityType,type:labels[entityType],title:String(item.title??''),subtitle:item.subtitle??subtitle,status:status||'匹配',path:`${route}?${params.toString()}`,projectId,yearId,versionId};
  }
  async function run(value:string){const q=value.trim();setSubmitted(q);setError('');if(!q){setResults([]);return;}setLoading(true);try{const payload=await api.get<SearchApiItem[]|{items:SearchApiItem[]}|{results:SearchApiItem[]}>(`/api/search?q=${encodeURIComponent(q)}`);const items=Array.isArray(payload)?payload:'items'in payload?payload.items:payload.results;setResults(items.map(normalizeResult));}catch(reason){setError(reason instanceof Error?reason.message:'搜索失败');}finally{setLoading(false);}}
  function openResult(item:SearchResult){if(item.projectId)setSelectedProject(item.projectId);if(item.yearId)setSelectedYear(item.yearId);if(item.versionId)setSelectedVersion(item.versionId);navigate(item.path);}
  useEffect(()=>{if(!query)return;const handle=window.setTimeout(()=>void run(query),450);return()=>window.clearTimeout(handle);},[query,options.projects,options.years,options.versions,user?.role]);
  const groups=useMemo(()=>Object.entries(results.reduce<Record<string,SearchResult[]>>((map,item)=>({...map,[item.type]:[...(map[item.type]??[]),item]}),{})),[results]);
  const iconFor=(entityType:SearchEntityType)=>entityType==='requirement'?<ClipboardCheck size={19}/>:entityType==='project'?<BriefcaseBusiness size={19}/>:entityType==='version'?<Tags size={19}/>:<FileStack size={19}/>;
  return <div className="page search-page"><PageHeader title="全局搜索" subtitle="定位需求、项目、版本、成果物与资金信息"/><form className="global-search" onSubmit={e=>{e.preventDefault();void run(query)}}><Search size={22}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="输入需求 ID、名称、项目或版本" autoFocus aria-label="全局搜索"/>{query&&<button type="button" onClick={()=>{setQuery('');setResults([]);setSubmitted('')}} aria-label="清空"><X size={19}/></button>}<Button type="submit">搜索</Button></form>{error&&<div className="data-state data-state--error" role="alert"><AlertCircle size={21}/><p>{error}</p></div>}{loading?<div className="search-skeleton" role="status"><span/>正在搜索</div>:submitted&&results.length===0?<Section><EmptyState icon={<Search size={30}/>} title={`未找到“${submitted}”的结果`}/></Section>:groups.length>0?<div className="search-results"><div className="search-summary">找到 <strong>{results.length}</strong> 条结果</div>{groups.map(([type,items])=><Section title={`${type} (${items.length})`} key={type}><div className="result-list">{items.map(item=><button key={`${type}-${item.id}`} onClick={()=>openResult(item)}><span className="result-icon">{iconFor(item.entityType)}</span><div><strong>{item.title}</strong><p>{item.subtitle}</p><small>{item.id}</small></div><StatusBadge tone={statusTone(item.status)}>{item.status}</StatusBadge><ArrowRight size={18}/></button>)}</div></Section>)}</div>:null}</div>;
}

interface Account{id:string;username:string;name:string;role:string;role_label:string;status:string;last_login:string;projects:string[];must_change_password:boolean}
const demoAccounts:Account[]=[];
const roles=[['admin','管理员'],['leader','咨询负责人'],['customer','客户'],['sales','销售'],['manager','项目经理'],['developer','研发人员'],['operator','运营人员']];
function accountItems(payload:Account[]|{items:Account[]}|{data:Account[]}){const values=Array.isArray(payload)?payload:'items'in payload?unwrapItems(payload):payload.data;return values.map(value=>{const raw=value as Account&{full_name?:string;is_active?:boolean;last_login_at?:string|null;project_ids?:Array<number|string>};if(raw.name)return value;const roleLabel=roles.find(item=>item[0]===raw.role)?.[1]??raw.role;return{id:String(raw.id),username:raw.username,name:raw.full_name??raw.username,role:raw.role,role_label:roleLabel,status:raw.is_active?'启用':'禁用',last_login:raw.last_login_at?new Date(raw.last_login_at).toLocaleString('zh-CN',{hour12:false}):'从未登录',projects:(raw.project_ids??[]).map(String),must_change_password:Boolean(raw.must_change_password)};});}

export function UsersPage(){
  const {notify,options,user}=useApp();const {data:raw,setData,loading,error}=useApiData<Account[]|{items:Account[]}|{data:Account[]}>('/api/users',demoAccounts);const items=accountItems(raw);const [query,setQuery]=useState('');const [open,setOpen]=useState(false);const [editing,setEditing]=useState<Account|null>(null);const [resetting,setResetting]=useState<Account|null>(null);const [tempPassword,setTempPassword]=useState('');const [form,setForm]=useState({username:'',name:'',role:'customer',password:'',projects:[] as string[]});const filtered=items.filter(i=>!query||`${i.username}${i.name}${i.role_label}`.toLowerCase().includes(query.toLowerCase()));
  async function create(e:FormEvent){e.preventDefault();try{const response=await api.post<Account>('/api/users',{username:form.username,full_name:form.name,role:form.role,initial_password:form.password,project_ids:form.role==='customer'?form.projects.map(Number):[]});const item=accountItems([response])[0];setData([...items,item]);setOpen(false);notify('账号已创建','用户首次登录时必须修改临时密码。');}catch(reason){notify('账号创建失败',reason instanceof Error?reason.message:'请稍后重试。','danger');}}
  async function saveEdit(){if(!editing)return;if(editing.id===user?.id){notify('不能在此修改当前账号','当前账号请通过个人密码入口维护，角色与停用操作需由其他管理员完成。','warning');return;}try{const response=await api.patch<Account>(`/api/users/${editing.id}`,{role:editing.role,is_active:editing.status==='启用',project_ids:editing.role==='customer'?editing.projects.map(Number):[]});const updated=accountItems([response])[0];setData(items.map(i=>i.id===editing.id?updated:i));setEditing(null);notify('用户权限已更新');}catch(reason){notify('权限更新失败',reason instanceof Error?reason.message:'请稍后重试。','danger');}}
  async function reset(){if(!resetting||tempPassword.length<10)return;if(resetting.id===user?.id){notify('不能重置当前账号','请使用修改密码功能；忘记当前管理员密码时由另一位管理员重置。','warning');return;}try{await api.post(`/api/users/${resetting.id}/reset-password`,{new_password:tempPassword});setData(items.map(i=>i.id===resetting.id?{...i,must_change_password:true}:i));setResetting(null);setTempPassword('');notify('密码已重置','该账号现有会话已失效，下次登录必须修改密码。');}catch(reason){notify('密码重置失败',reason instanceof Error?reason.message:'请稍后重试。','danger');}}
  return <div className="page"><PageHeader title="用户与权限" subtitle="账号由管理员创建，按角色和项目授权" actions={<Button onClick={()=>setOpen(true)}><Plus size={17}/>新建账号</Button>}/><div className="security-notice"><ShieldCheck size={21}/><div><strong>账号安全策略</strong><p>不开放自助注册。忘记密码由其他管理员重置；同一账号新登录后，原会话立即失效。</p></div></div><DataState loading={loading} error={error}><div className="metrics-grid"><Metric label="全部用户" value={items.length} icon={<Users size={19}/>}/><Metric label="管理员账号" value={items.filter(i=>i.role==='admin'&&i.status==='启用').length} tone="success"/><Metric label="已启用账号" value={items.filter(i=>i.status==='启用').length}/><Metric label="待首次改密" value={items.filter(i=>i.must_change_password).length} tone="warning"/></div><div className="filter-bar"><label className="search-input"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索姓名、账号或角色" aria-label="搜索用户"/></label><span className="table-count">{filtered.length} 个账号</span></div><Section><div className="table-wrap"><table className="data-table"><thead><tr><th>用户</th><th>角色</th><th>项目权限</th><th>最后登录</th><th>状态</th><th><span className="sr-only">操作</span></th></tr></thead><tbody>{filtered.map(account=><tr key={account.id}><td><div className="user-cell"><span className="avatar">{account.name.slice(0,1)}</span><span><strong>{account.name}</strong><small>{account.username}{account.id===user?.id?' · 当前账号':''}</small></span></div></td><td>{account.role_label}</td><td>{account.role==='customer'?account.projects.length?`${account.projects.length} 个项目`:'未授权项目':'全部项目'}</td><td>{account.last_login}</td><td><StatusBadge tone={statusTone(account.status)}>{account.status}</StatusBadge></td><td><div className="row-actions"><button className="icon-button" title="重置密码" aria-label={`重置 ${account.name} 密码`} onClick={()=>setResetting(account)}><KeyRound size={18}/></button><button className="icon-button" title="编辑权限" aria-label={`编辑 ${account.name} 权限`} onClick={()=>setEditing({...account})}><UserCog size={18}/></button></div></td></tr>)}</tbody></table></div></Section></DataState>
    <Modal open={open} title="新建用户账号" wide onClose={()=>setOpen(false)} footer={<><Button variant="secondary" onClick={()=>setOpen(false)}>取消</Button><Button type="submit" form="account-form">创建账号</Button></>}><form id="account-form" className="form-grid" onSubmit={e=>void create(e)}><label className="field"><span>登录账号</span><input value={form.username} onChange={e=>setForm({...form,username:e.target.value})} autoComplete="off" required/></label><label className="field"><span>用户姓名</span><input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/></label><label className="field"><span>角色</span><select value={form.role} onChange={e=>{const role=e.target.value;setForm({...form,role,projects:role==='customer'?form.projects:[]})}}>{roles.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label className="field"><span>临时密码</span><input type="password" minLength={10} value={form.password} onChange={e=>setForm({...form,password:e.target.value})} autoComplete="new-password" required/><small>至少 10 位，包含大小写字母、数字和特殊字符；首次登录时强制修改</small></label>{form.role==='customer'?<fieldset className="field field--wide project-picker"><legend>客户可访问项目</legend>{options.projects.map(project=><label key={project.id}><input type="checkbox" checked={form.projects.includes(project.id)} onChange={e=>setForm({...form,projects:e.target.checked?[...form.projects,project.id]:form.projects.filter(id=>id!==project.id)})}/><span>{project.name}</span></label>)}</fieldset>:<div className="permission-scope field--wide"><span>项目权限</span><strong>全部项目</strong></div>}</form></Modal>
    <Modal open={Boolean(editing)} title="编辑角色与项目权限" wide onClose={()=>setEditing(null)} footer={<><Button variant="secondary" onClick={()=>setEditing(null)}>取消</Button><Button onClick={()=>void saveEdit()}><Check size={17}/>保存权限</Button></>}>{editing&&<div className="form-grid"><div className="edit-user-heading field--wide"><span className="avatar">{editing.name.slice(0,1)}</span><div><strong>{editing.name}</strong><small>{editing.username}</small></div></div><label className="field"><span>角色</span><select value={editing.role} onChange={e=>{const role=e.target.value;setEditing({...editing,role,role_label:roles.find(r=>r[0]===role)?.[1]??role,projects:role==='customer'?editing.projects:[]})}}>{roles.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label className="field"><span>账号状态</span><select value={editing.status} onChange={e=>setEditing({...editing,status:e.target.value})}><option>启用</option><option>禁用</option></select></label>{editing.role==='customer'?<fieldset className="field field--wide project-picker"><legend>客户可访问项目</legend>{options.projects.map(project=><label key={project.id}><input type="checkbox" checked={editing.projects.includes(project.id)} onChange={e=>setEditing({...editing,projects:e.target.checked?[...editing.projects,project.id]:editing.projects.filter(id=>id!==project.id)})}/><span>{project.name}</span></label>)}</fieldset>:<div className="permission-scope field--wide"><span>项目权限</span><strong>全部项目</strong></div>}</div>}</Modal>
    <Modal open={Boolean(resetting)} title="重置用户密码" onClose={()=>setResetting(null)} footer={<><Button variant="secondary" onClick={()=>setResetting(null)}>取消</Button><Button disabled={!(tempPassword.length>=10&&/[a-z]/.test(tempPassword)&&/[A-Z]/.test(tempPassword)&&/\d/.test(tempPassword)&&/[^A-Za-z\d]/.test(tempPassword))} onClick={()=>void reset()}><KeyRound size={17}/>确认重置</Button></>}><div className="reset-password"><LockKeyhole size={28}/><p>正在为 <strong>{resetting?.name}</strong>（{resetting?.username}）重置密码。确认后其现有会话立即失效。</p><label className="field"><span>新临时密码</span><input type="password" minLength={10} value={tempPassword} onChange={e=>setTempPassword(e.target.value)} autoComplete="new-password"/><small>至少 10 位，包含大小写字母、数字和特殊字符</small></label></div></Modal>
  </div>;
}

interface AuditEntry{id:string;time:string;occurredAt:string;operator:string;role:string;action:string;actionCode:string;target_type:string;target:string;ip:string;result:string;before?:string;after?:string}
const demoAudit:AuditEntry[]=[];
function auditItems(payload:AuditEntry[]|{items:AuditEntry[]}|{data:AuditEntry[]}){const values=Array.isArray(payload)?payload:'items'in payload?unwrapItems(payload):payload.data;const actionLabels:Record<string,string>={create:'创建',update:'更新',delete:'删除',disable:'停用账号',transition:'状态流转',login:'登录',login_failed:'登录失败',login_blocked:'登录受限',permission_denied:'权限拒绝',logout:'退出',freeze:'冻结基线',release:'发布版本',upload:'上传文件',submit:'提交审批',approve:'审批通过',reject:'审批驳回',apply:'执行变更',change_password:'修改密码',reset_password:'重置密码'};return values.map(value=>{const raw=value as AuditEntry&{created_at?:string;actor_id?:number;entity_type?:string;entity_id?:string;ip_address?:string;before_data?:unknown;after_data?:unknown};if(raw.time)return value;const print=(data:unknown)=>data?JSON.stringify(data,null,2):undefined;const actionCode=String(raw.action);const failed=['login_failed','login_blocked','permission_denied'].includes(actionCode);return{id:String(raw.id),time:raw.created_at?new Date(raw.created_at).toLocaleString('zh-CN',{hour12:false}):'',occurredAt:raw.created_at??'',operator:raw.actor_id?`用户 #${raw.actor_id}`:'系统',role:'-',action:actionLabels[actionCode]??actionCode,actionCode,target_type:raw.entity_type??'',target:raw.entity_id?`#${raw.entity_id}`:'-',ip:raw.ip_address??'-',result:failed?'失败':'成功',before:print(raw.before_data),after:print(raw.after_data)};});}
function exportAudit(items:AuditEntry[]){const rows=[['时间','操作人','角色','操作','对象','IP','结果'],...items.map(i=>[i.time,i.operator,i.role,i.action,i.target,i.ip,i.result])];const escape=(value:string)=>{const protectedValue=/^[ \t\r\n]*[=+\-@]/.test(value)?`'${value}`:value;return `"${protectedValue.replaceAll('"','""')}"`;};const blob=new Blob([`\uFEFF${rows.map(row=>row.map(value=>escape(String(value??''))).join(',')).join('\r\n')}`],{type:'text/csv'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`审计日志-${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(url);}

export function AuditPage(){
  const {notify}=useApp();const {data:raw,loading,error}=useApiData<AuditEntry[]|{items:AuditEntry[]}|{data:AuditEntry[]}>('/api/audit',demoAudit);const items=auditItems(raw);const [action,setAction]=useState('');const [result,setResult]=useState('');const [detail,setDetail]=useState<AuditEntry|null>(null);const filtered=items.filter(i=>(!action||i.action===action)&&(!result||i.result===result));const today=new Date();const todayCount=items.filter(item=>{if(!item.occurredAt)return false;const date=new Date(item.occurredAt);return date.getFullYear()===today.getFullYear()&&date.getMonth()===today.getMonth()&&date.getDate()===today.getDate();}).length;
  return <div className="page"><PageHeader title="审计日志" subtitle="追溯需求状态、资金、权限与登录安全变更" actions={<Button variant="secondary" onClick={()=>{exportAudit(filtered);notify('审计日志已导出')}}><Download size={17}/>导出日志</Button>}/><DataState loading={loading} error={error}><div className="metrics-grid"><Metric label="今日操作" value={todayCount} icon={<FileClock size={19}/>}/><Metric label="状态流转" value={items.filter(i=>i.actionCode==='transition').length} tone="warning"/><Metric label="登录失败" value={items.filter(i=>['login_failed','login_blocked'].includes(i.actionCode)).length} tone="danger"/><Metric label="当前加载" value={`${items.length} 条`}/></div><div className="filter-bar"><label className="select-filter"><Filter size={17}/><select value={action} onChange={e=>setAction(e.target.value)} aria-label="操作类型"><option value="">全部操作</option>{[...new Set(items.map(i=>i.action))].map(v=><option key={v}>{v}</option>)}</select></label><label className="select-filter"><select value={result} onChange={e=>setResult(e.target.value)} aria-label="操作结果"><option value="">全部结果</option><option>成功</option><option>失败</option></select></label><span className="table-count">展示 {filtered.length} 条</span></div><Section><div className="table-wrap"><table className="data-table"><thead><tr><th>时间</th><th>操作人</th><th>操作</th><th>对象</th><th>IP 地址</th><th>结果</th><th><span className="sr-only">操作</span></th></tr></thead><tbody>{filtered.map(entry=><tr key={entry.id}><td>{entry.time}</td><td><strong>{entry.operator}</strong><small>{entry.role}</small></td><td>{entry.action}</td><td><small>{entry.target_type}</small><strong>{entry.target}</strong></td><td><code>{entry.ip}</code></td><td><StatusBadge tone={entry.result==='成功'?'success':'danger'}>{entry.result}</StatusBadge></td><td><button className="icon-button" onClick={()=>setDetail(entry)} aria-label={`查看 ${entry.id}`}><ExternalLink size={17}/></button></td></tr>)}</tbody></table></div></Section></DataState><Modal open={Boolean(detail)} title="审计记录详情" onClose={()=>setDetail(null)}>{detail&&<div className="audit-detail"><div><small>日志编号</small><strong>{detail.id}</strong></div><dl><div><dt>操作时间</dt><dd>{detail.time}</dd></div><div><dt>操作人</dt><dd>{detail.operator} · {detail.role}</dd></div><div><dt>来源 IP</dt><dd>{detail.ip}</dd></div><div><dt>操作结果</dt><dd>{detail.result}</dd></div></dl>{(detail.before||detail.after)&&<div className="audit-diff"><div><small>变更前</small><p>{detail.before}</p></div><ArrowRight size={20}/><div><small>变更后</small><p>{detail.after}</p></div></div>}</div>}</Modal></div>;
}
